// ═══════════════════════════════════════════════════════════════
// AUTO-GENERATED BY ROUTE-SAGE — DO NOT EDIT MANUALLY
// ═══════════════════════════════════════════════════════════════
// Generated: 2026-10-02T04:56:32.950Z
// Version: route-sage@3.2.0
// Source: src/routes
// Config: route-sage.config.json
//
// Regenerate: npx route-sage
// Watch:       npx route-sage --watch
// Docs:        https://github.com/P-Technologies/route-sage#readme
// Machine-readable: __routeSageMeta
// ═══════════════════════════════════════════════════════════════
import { createPathConfig } from "route-sage";

const rawConfig = {
  /**
   * **Route**: `/`
   * **Source**: `src/routes/page.tsx`
   */
  "home": () => ({
    url: `/`,
    file: "src/routes/page.tsx",
  }),
  /**
   * **Route**: `/add-pet`
   * **Source**: `src/routes/add-pet/page.tsx`
   */
  "add-pet": () => ({
    url: `/add-pet`,
    file: "src/routes/add-pet/page.tsx",
  }),
  /**
   * **Route**: `/catalog`
   * **Source**: `src/routes/catalog/page.tsx`
   */
  "catalog": () => ({
    url: `/catalog`,
    file: "src/routes/catalog/page.tsx",
  }),
  /**
   * **Route**: `/orders`
   * **Source**: `src/routes/orders/page.tsx`
   */
  "orders": () => ({
    url: `/orders`,
    file: "src/routes/orders/page.tsx",
  }),
  /**
   * **Route**: `/pets`
   */
  "pets": () => ({
    url: `/pets`,
    /**
     * **Route**: `/${petId}`
     * **Source**: `src/routes/pets/[petId]/page.tsx`
     */
    "$petId": (petId: string) => ({
      url: `/${petId}`,
      file: "src/routes/pets/[petId]/page.tsx",
    }),
  }),
  /**
   * **Route**: `/users`
   */
  "users": () => ({
    url: `/users`,
    /**
     * **Route**: `/${userId}`
     */
    "$userId": (userId: string) => ({
      url: `/${userId}`,
      /**
       * **Route**: `/profile`
       * **Source**: `src/routes/users/[userId]/profile/page.tsx`
       */
      "profile": () => ({
        url: `/profile`,
        file: "src/routes/users/[userId]/profile/page.tsx",
      }),
    }),
  }),
}
const { routes, groups } = createPathConfig(rawConfig);

export default routes;
export { groups };

export const routeStats = {
  "totalRoutes": 9,
  "dynamicRoutes": 2,
  "staticRoutes": 7,
  "maxDepth": 3,
  "generatedAt": "2026-10-02T04:56:32.950Z",
  "generatedBy": "route-sage@3.2.0",
  "sourceRoot": "src/routes"
} as const;

export const __routeSageMeta = {
  "version": "3.2.0",
  "sourceRoot": "src/routes",
  "generatedAt": "2026-10-02T04:56:32.950Z",
  "regenerate": "npx route-sage"
} as const;

export type AppRoute =
  | "/"
  | "/add-pet"
  | "/catalog"
  | "/orders"
  | "/pets"
  | `/pets/${string}`
  | "/users"
  | `/users/${string}`
  | `/users/${string}/profile`;

export type RouteName =
  | "home"
  | "add-pet"
  | "catalog"
  | "orders"
  | "pets"
  | "users"
  | "users.profile";
